from pathlib import Path


JETSON_ROOT = Path(__file__).resolve().parent

ARDUINO_PORT = "/dev/ttyUSB0"
GPS_PORT = "/dev/ttyUSB1"
GPS_ORIGIN = (47.608013, -122.335167)
ZERO_IMU_ON_START = True

WHEEL_DIAMETER_CM = 10.16
TRACK_WIDTH_CM = 34.826
MAX_FORWARD_CM_PER_SEC = 30.0
MAX_TURN_DEG_PER_SEC = 60.0

LEFT_MOTOR = {
    "pwm_pin": 9,
    "dir_pin": 8,
    "encoder_index": 2,
    "encoder_reversed": True,
}

RIGHT_MOTOR = {
    "pwm_pin": 10,
    "dir_pin": 7,
    "encoder_index": 1,
    "encoder_reversed": True,
}

MOTOR_TUNING = {
    "kp": 0.2,
    "ki": 0.08,
    "kd": 0.0,
    "static_ff_pwm": 15.0,
    "velocity_ff_pwm_per_deg_per_sec": 0.108,
}

NAV_MAX_MAP_DISTANCE_M = 0.5
NAV_GRID_RESOLUTION_M = 0.4
NAV_CLEARANCE_COST_WEIGHT = 3.0
NAV_ENDPOINT_SNAP_MAX_DISTANCE_M = 7.0
NAV_GPS_SNAP_ENABLED = True
NAV_GPS_SNAP_MAX_DISTANCE_M = 25.0
NAV_GPS_SNAP_MAP_TOLERANCE_M = 0.5
NAV_MAP_PATH = JETSON_ROOT / "maps" / "drawn_overlake_campus_map.json"
NAV_DEFAULT_DESTINATION_X_M = 12777.302
NAV_DEFAULT_DESTINATION_Y_M = 4029.061
NAV_CONTROL_INTERVAL_SEC = 0.05
NAV_WAYPOINT_REACHED_DISTANCE_M = 0.35
NAV_DESTINATION_REACHED_DISTANCE_M = 0.30
NAV_WAYPOINT_TIMEOUT_SEC = None
NAV_ROUTE_TIMEOUT_SEC = None
NAV_LOG_INTERVAL_SEC = 1.0

NAV_ENABLE_VIDEO_FEEDBACK = True
NAV_VIDEO_FEEDBACK_ROI_TOP_FRACTION = 0.25
NAV_VIDEO_FEEDBACK_ROI_BOTTOM_FRACTION = 0.78
NAV_VIDEO_FEEDBACK_MIN_TRAIL_FRACTION = 0.01
NAV_VIDEO_FEEDBACK_MIN_TRAIL_PIXELS = 80
NAV_VIDEO_FEEDBACK_SMOOTHING = 0.25
NAV_VIDEO_FEEDBACK_ANGLE_KP_DEG = 20.0
NAV_VIDEO_FEEDBACK_NEAR_DISTANCE_M = 20.0
NAV_VIDEO_FEEDBACK_FAR_DISTANCE_M = 40.0
NAV_VIDEO_FEEDBACK_FAR_ANGLE_CORRECTION_DEG = 10.0
NAV_VIDEO_FEEDBACK_NEAR_ANGLE_CORRECTION_DEG = 30.0

TRAIL_FOLLOW_FORWARD_CM_PER_SEC = MAX_FORWARD_CM_PER_SEC
TRAIL_FOLLOW_MAX_TURN_DEG_PER_SEC = min(35.0, MAX_TURN_DEG_PER_SEC)
TRAIL_FOLLOW_NO_TRAIL_TIMEOUT_SEC = 1.0

NAV_VIDEO_FEEDBACK_FORWARD_CM_PER_SEC = TRAIL_FOLLOW_FORWARD_CM_PER_SEC
NAV_VIDEO_FEEDBACK_MAX_TURN_DEG_PER_SEC = TRAIL_FOLLOW_MAX_TURN_DEG_PER_SEC
NAV_VIDEO_FEEDBACK_NO_TRAIL_TIMEOUT_SEC = TRAIL_FOLLOW_NO_TRAIL_TIMEOUT_SEC
NAV_VIDEO_FEEDBACK_DEADBAND = 0.01
NAV_VIDEO_FEEDBACK_MAX_OFFSET_STEP = 2.0
NAV_VIDEO_FEEDBACK_MIN_ROW_TRAIL_PIXELS = 4
NAV_VIDEO_FEEDBACK_MAX_ROW_TRAIL_FRACTION = 0.95
NAV_VIDEO_FEEDBACK_TOP_WEIGHT = 0.0
NAV_VIDEO_FEEDBACK_BOTTOM_WEIGHT = 0.0
NAV_VIDEO_FEEDBACK_ROUTE_ALIGNMENT_DEG = 35.0
NAV_VIDEO_FEEDBACK_FAR_ROUTE_ALIGNMENT_DEG = 20.0
NAV_VIDEO_FEEDBACK_ROUTE_TURN_SCALE = 0.25
NAV_VIDEO_FEEDBACK_FAR_CORRECTION_SCALE = 0.5
NAV_VIDEO_FEEDBACK_TURN_SMOOTHING = 1.0
NAV_VIDEO_FEEDBACK_MAX_TURN_STEP_DEG_PER_SEC = 0.0
NAV_VIDEO_FEEDBACK_TURN_IN_PLACE_DEG = 15.0

CAMERA_URI = "/dev/video0"
CAMERA_INPUT_WIDTH = 640
CAMERA_INPUT_HEIGHT = 480
CAMERA_INPUT_RATE = 10
CAMERA_INPUT_FLIP = None
CAMERA_V4L2_CONTROLS = {
    "auto_exposure": 1,
    "exposure_auto_priority": 0,
    "exposure_time_absolute": 2,
    "gain": 0,
    "brightness": 0,
    "backlight_compensation": 0,
}
CAMERA_AUTO_EXPOSURE = {
    "enabled": True,
    "min_value": 2,
    "max_value": 14,
    "initial_value": 2,
    "target_luma": 105.0,
    "deadband": 14.0,
    "interval_sec": 0.35,
    "max_step": 1,
}
CAMERA_DEEPSCENE_ENABLED = True
CAMERA_DEBUG_STREAM_ENABLED = True
