from pathlib import Path


JETSON_ROOT = Path(__file__).resolve().parent

ARDUINO_PORT = "/dev/ttyUSB1"
GPS_PORT = "/dev/ttyUSB0"
GPS_ORIGIN = (47.608013, -122.335167)
ZERO_IMU_ON_START = True

WHEEL_DIAMETER_CM = 10.16
TRACK_WIDTH_CM = 34.826
MAX_FORWARD_CM_PER_SEC = 30.0
MAX_TURN_DEG_PER_SEC = 45.0

LEFT_MOTOR = {
    "pwm_pin": 9,
    "dir_pin": 8,
    "encoder_index": 2,
    "encoder_reversed": True,
}

RIGHT_MOTOR = {
    "pwm_pin": 10,
    "dir_pin": 7,
    "encoder_index": 1,
    "encoder_reversed": True,
}

MOTOR_TUNING = {
    "kp": 0.2,
    "ki": 0.08,
    "kd": 0.0,
    "static_ff_pwm": 15.0,
    "velocity_ff_pwm_per_deg_per_sec": 0.108,
}

NAV_MAX_MAP_DISTANCE_M = 1.0
NAV_GRID_RESOLUTION_M = 0.4
NAV_CLEARANCE_COST_WEIGHT = 1.5
NAV_ENDPOINT_SNAP_MAX_DISTANCE_M = 10
NAV_MAP_PATH = JETSON_ROOT / "maps" / "overlake_campus_map.json"
NAV_DEFAULT_DESTINATION_X_M = 12777.302
NAV_DEFAULT_DESTINATION_Y_M = 4029.061
NAV_CONTROL_INTERVAL_SEC = 0.05
NAV_WAYPOINT_REACHED_DISTANCE_M = 0.35
NAV_DESTINATION_REACHED_DISTANCE_M = 0.30
NAV_WAYPOINT_TIMEOUT_SEC = None
NAV_ROUTE_TIMEOUT_SEC = None
NAV_LOG_INTERVAL_SEC = 1.0

NAV_ENABLE_VIDEO_FEEDBACK = False
NAV_VIDEO_FEEDBACK_LOOKAHEAD_M = 1.2
NAV_VIDEO_FEEDBACK_MAX_LATERAL_CORRECTION_M = 0.55
NAV_VIDEO_FEEDBACK_ROI_TOP_FRACTION = 0.45
NAV_VIDEO_FEEDBACK_ROI_BOTTOM_FRACTION = 0.95
NAV_VIDEO_FEEDBACK_MIN_TRAIL_FRACTION = 0.01
NAV_VIDEO_FEEDBACK_MIN_TRAIL_PIXELS = 80
NAV_VIDEO_FEEDBACK_BOTTOM_WEIGHT = 2.0

CAMERA_URI = "/dev/video0"
CAMERA_INPUT_WIDTH = 640
CAMERA_INPUT_HEIGHT = 480
CAMERA_INPUT_RATE = 10
CAMERA_INPUT_FLIP = None
CAMERA_V4L2_CONTROLS = {
    "auto_exposure": 1,
    "exposure_time_absolute": 20,
    "gain": 0,
    "brightness": 0,
    "backlight_compensation": 0,
}
CAMERA_DEEPSCENE_ENABLED = False
CAMERA_DEBUG_STREAM_ENABLED = True
